extend type Query {
  me: Me! @isAuthenticated
}

extend type Mutation {
  signup(email: String!, password: String!): AuthData
  login(email: String!, password: String!): AuthData
}

type AuthData {
  user: Me
}

type Me {
  _id: ID!
  name: String
  email: String!
  token: String
}
